### ISSUE TITLE
IG publisher too strong checking logical IDs in the entry list. (Duplicate id value)

### ISSUE THREAD

**Issue by DavidGutknecht** [HL7/fhir-ig-publisher#144] opened 2020-08-03 09:44 UTC
How to reproduce :
  Create a bundle with two entries from different types, and give the two entries the same logical id
  For example:
```"entry": [
              {
            "fullUrl": "Procedure/1",
            "resource": {
                "resourceType": "Procedure",
                "id": "1",
[...]
{
            "fullUrl": "Condition/1",
            "resource": {
                "resourceType": "Condition",
                "id": "1",
```
By compiling you will get the error message : ```Duplicate id value '1'```

In the documentation http://hl7.org/fhir/R4/resource.html#id the logical id is defined as
```The logical id is unique within the space of all resources of the same type on the same server```.

In this case the two entries are from different types I assume that we could be able to use the same id.

Best regards,
David

**Comment by grahamegrieve** [comment] 2020-08-03 11:50
I can't reproduce this. Tried with 

{
  "resourceType": "Bundle",
  "id": "bundle-duplicate-id",
  "type": "collection",
  "entry": [
    {
      "fullUrl": "Patient/1",
      "resource": {
          "resourceType": "Patient",
          "id" : "1"
        }
    },
    {
      "fullUrl": "RelatedPerson/1",
      "resource": {
        "resourceType": "RelatedPerson",
        "id" : "1",
        "patient" : { "reference" : "Patient/1" }
      }
    }
  ]
}

Either close this, or refer to an IG on github that demonstrates the problem

**Comment by DavidGutknecht** [comment] 2020-08-03 12:52
Thanks, strange, 
My bundle is from type "collection".
I will try to produce some example for you.

**Comment by DavidGutknecht** [comment] 2020-08-03 15:41
Hello Graham, 
just as information, I'm still investigating.
On a simplified version of my bundle I don't get any error, but on the full version of my bundle I have the error message.
And with the same bundle if I put unique Ids other the bundle I don't get any errors.
I will have to do some trial/error by progressively reduce the full bundle that generates the error.
Maybe you can help me: is there an easy way to validate a bundle example using the publisher or another tool without recompiling the full IG ? I saw there is the option -source and -destination, but it is not clear how to use it.

**Comment by grahamegrieve** [comment] 2020-08-03 19:34
well, the error appears to be coming from the validator, though I don't think you copied the entire error. If so, you can just validate the bundle directly using the java validator. You might be better asking questions like this on https://chat.fhir.org/#narrow/stream/179252-IG-creation

**Comment by lmckenzi** [comment] 2022-10-04 21:37
@DavidGutknecht is this still an issue, or can we close the tracker?

**Comment by DavidGutknecht** [comment] 2022-10-05 06:02
The tracker can be closed.

**Closed** 2022-10-05 06:02 UTC
Labels: cant-reproduce
